version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/npocoazure-ci/api/v2/package
  api_key:
    secure: QqTnjOhBWYBj60GLoXKJZEFKjMY++qPNLAL2cdvcCKVv0RFckHvKA7nJ+SUlvxjL
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key: H840IdbJKV97Lcvd0ZQ0sN3lCayII5QAhPD1Kiw5sz9iMvfO5UWkupj4ZaJ43eph
    secure: 
  on:
    branch: master
    appveyor_repo_tag: true